name: Build moOde Image
on: workflow_dispatch # Allows you to click a button to start the build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Build Script
        run: |
          sudo ./build.sh

      - name: Upload Finished Image
        uses: actions/upload-artifact@v4
        with:
          name: moode-img
          path: deploy/*.zip
